const OPPORTUNITY_ID_PATTERN = /^[A-Za-z0-9_-]{1,128}$/;
const REQUEST_ID_PATTERN = /^[A-Za-z0-9_-]{8,128}$/;

/**
 * Validates a public opportunity document identifier.
 * @param {unknown} value Candidate identifier.
 * @return {string} Validated identifier.
 */
export function requireOpportunityId(value: unknown): string {
  if (typeof value !== "string" || !OPPORTUNITY_ID_PATTERN.test(value)) {
    throw new Error("A valid opportunityId is required");
  }
  return value;
}

/**
 * Validates an idempotency identifier generated by the client.
 * @param {unknown} value Candidate request identifier.
 * @return {string} Validated request identifier.
 */
export function requireOpportunityRequestId(value: unknown): string {
  if (typeof value !== "string" || !REQUEST_ID_PATTERN.test(value)) {
    throw new Error("A valid requestId is required");
  }
  return value;
}

/**
 * Validates a partner handoff URL before returning it to a student.
 * @param {unknown} value Candidate action URL.
 * @return {string} Normalized HTTPS URL.
 */
export function requireHttpsActionUrl(value: unknown): string {
  if (typeof value !== "string") {
    throw new Error("Opportunity action URL is missing");
  }

  const parsed = new URL(value);
  if (parsed.protocol !== "https:" || parsed.username || parsed.password) {
    throw new Error("Opportunity action URL must use HTTPS");
  }
  return parsed.toString();
}

/**
 * Checks whether an opportunity is published within its active window.
 * @param {Record<string, unknown>} data Opportunity document data.
 * @param {number} nowMs Current time in milliseconds.
 * @return {boolean} Whether the opportunity is currently available.
 */
export function isOpportunityAvailable(
  data: Record<string, unknown>,
  nowMs: number,
): boolean {
  if (data.status !== "published") return false;

  const publishedAt = data.publishedAt as {toMillis?: () => number} | undefined;
  if (publishedAt?.toMillis && publishedAt.toMillis() > nowMs) return false;

  const expiresAt = data.expiresAt as {toMillis?: () => number} | undefined;
  if (expiresAt?.toMillis && expiresAt.toMillis() <= nowMs) return false;

  return true;
}
